FROM python:2-alpine

LABEL org.opencontainers.image.source https://github.com/joshhighet/gotham
LABEL upstream=https://github.com/sqlmapproject/sqlmap

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN pip install bs4

WORKDIR /root
RUN git clone https://github.com/sqlmapproject/sqlmap.git sqlmap
RUN chmod +x /root/sqlmap/sqlmap.py
RUN ln -s /root/sqlmap/sqlmap.py /usr/bin/sqlmap

ENTRYPOINT ["sqlmap"]
